# Generated by Django 2.2.5 on 2019-10-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
